### ISSUE TITLE
BridgeController.showall() method filters results if there are no interfaces attached to bridge

### ISSUE THREAD

**Issue by edjaguilar** [udragon/pybrctl#1]
If there are no interfaces attached in a bridge, resulting elements read by line is 3 instead of 4 and the result is filtered in:
https://github.com/udragon/pybrctl/blob/master/pybrctl/pybrctl.py#L129

**Comment by udragon** [comment]
Bug fixed.
Reference: https://github.com/udragon/pybrctl/commit/48f748b29449c5da37053c4fa41319a5af730ae0
