### ISSUE TITLE
Path to brctl is fixed

### ISSUE THREAD

**Issue by vvgelder** [udragon/pybrctl#2]
Hi,

At centos 6 the path to brctl is /usr/sbin/brctl and not /sbin/brctl. So your code is not working.

Suggestion:

```
from distutils import spawn
brctlexe = spawn.find_executable("brctl")
```

**Comment by udragon** [comment]
Issue fixed.
reference: https://github.com/udragon/pybrctl/commit/3a17effd0ea7000e6f9fb4fcce68e819cc4c1530
