### ISSUE TITLE
Revert:  showall() function bug fixed

### ISSUE THREAD

**Issue by techaddicted** [udragon/pybrctl#4]
The commit 48f748b29449c5da37053c4fa41319a5af730ae0 did not fixed the bug, it introduced more problems.

When using 
`brwlist = filter(lambda x: len(x) == 3, wlist)`

No bridges are found.
After reverting the change so that the code is
`brwlist = filter(lambda x: len(x) == 4, wlist)`

Bridges are found as expected

**Comment by udragon** [comment]
Fixed this line with:
`brwlist = filter(lambda x: len(x) != 1 wlist)`

Please test and confirm and I will close the issue.

**Comment by techaddicted** [comment]
Looks good!
`brwlist = filter(lambda x: len(x) != 1, wlist)`
works.

Thank you for the quick fix
